package com.github.muellerc.techforum2016.jboss.pricing.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-23T21:48:58.970+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PricingService", 
                  wsdlLocation = "file:/Users/cmueller/workspaceGitHub/techforum-2016-from-fuse-transform-to-jboss/book-search-jboss/interfaces/pricing-service/src/main/resources/techforum-sample.wsdl",
                  targetNamespace = "http://www.company.de/techforum/service") 
public class PricingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.company.de/techforum/service", "PricingService");
    public final static QName PricingService = new QName("http://www.company.de/techforum/service", "PricingService");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/cmueller/workspaceGitHub/techforum-2016-from-fuse-transform-to-jboss/book-search-jboss/interfaces/pricing-service/src/main/resources/techforum-sample.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PricingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/cmueller/workspaceGitHub/techforum-2016-from-fuse-transform-to-jboss/book-search-jboss/interfaces/pricing-service/src/main/resources/techforum-sample.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PricingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PricingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PricingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PricingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PricingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PricingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PricingServicePort
     */
    @WebEndpoint(name = "PricingService")
    public PricingServicePort getPricingService() {
        return super.getPort(PricingService, PricingServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PricingServicePort
     */
    @WebEndpoint(name = "PricingService")
    public PricingServicePort getPricingService(WebServiceFeature... features) {
        return super.getPort(PricingService, PricingServicePort.class, features);
    }

}
