package com.github.muellerc.techforum2016.jboss.pricing.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-23T21:48:58.957+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.company.de/techforum/service", name = "PricingServicePort")
@XmlSeeAlso({com.github.muellerc.techforum2016.jboss.pricing.model.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PricingServicePort {

    @WebMethod(action = "http://www.company.de/techforum/service/getBookPrice")
    @WebResult(name = "getBookPriceResponse", targetNamespace = "http://www.company.de/techforum/data", partName = "parameters")
    public com.github.muellerc.techforum2016.jboss.pricing.model.GetBookPriceResponse getBookPrice(
        @WebParam(partName = "parameters", name = "getBookPriceRequest", targetNamespace = "http://www.company.de/techforum/data")
        com.github.muellerc.techforum2016.jboss.pricing.model.GetBookPriceRequest parameters
    ) throws ServiceException;
}
