
package com.github.muellerc.techforum2016.jboss.pricing.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-23T21:48:58.934+02:00
 * Generated source version: 3.1.5
 */

@WebFault(name = "serviceException", targetNamespace = "http://www.company.de/techforum/data")
public class ServiceException extends Exception {
    
    private com.github.muellerc.techforum2016.jboss.pricing.model.ServiceException serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.github.muellerc.techforum2016.jboss.pricing.model.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, com.github.muellerc.techforum2016.jboss.pricing.model.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public com.github.muellerc.techforum2016.jboss.pricing.model.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
